name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Checkout test runner
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          repository: exercism/8th-test-runner
          token: ${{ secrets.TEST_RUNNER_PAT }}
          path: 8th-test-runner
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: 8th-test-runner
          push: false
          load: true
          tags: exercism/8th-test-runner:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ZIP_PASSWORD=${{secrets.ZIP_PASSWORD}}

      - name: Run tests for all exercises
        run: bin/verify-exercises-in-docker
