name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Checkout test runner
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          repository: exercism/8th-test-runner
          token: ${{ secrets.TEST_RUNNER_PAT }}
          path: 8th-test-runner
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5
        with:
          install: true

      - name: Build and push
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991
        with:
          context: 8th-test-runner
          push: false
          load: true
          tags: exercism/8th-test-runner:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ZIP_PASSWORD=${{secrets.ZIP_PASSWORD}}

      - name: Run tests for all exercises
        run: bin/verify-exercises-in-docker
