name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Checkout test runner
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          repository: exercism/8th-test-runner
          token: ${{ secrets.TEST_RUNNER_PAT }}
          path: 8th-test-runner
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325
        with:
          install: true

      - name: Build and push
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: 8th-test-runner
          push: false
          load: true
          tags: exercism/8th-test-runner:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ZIP_PASSWORD=${{secrets.ZIP_PASSWORD}}

      - name: Run tests for all exercises
        run: bin/test
